// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'approve-button': string;
  'approvemodal-container': string;
  'approvemodal-content': string;
  'company-logo': string;
  'components': string;
  'image': string;
}
export const cssExports: CssExports;
export default cssExports;
