// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'approve-button': string;
  'button-general-style': string;
  'buttons': string;
  'cancel-button': string;
  'company-logo': string;
  'components': string;
  'forgotpass-container': string;
  'forgotpass-content': string;
  'image': string;
}
export const cssExports: CssExports;
export default cssExports;
