// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'loadingmodal-container': string;
  'loadingmodal-content': string;
}
export const cssExports: CssExports;
export default cssExports;
