// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content-slideone': string;
  'content-slidethree': string;
  'content-slidetwo': string;
  'slideone': string;
  'slider-button': string;
  'slidethree': string;
  'slidetwo': string;
  'title-slideone': string;
  'title-slidethree': string;
  'title-slidetwo': string;
}
export const cssExports: CssExports;
export default cssExports;
