// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'amount-info': string;
  'buttons': string;
  'cart-container': string;
  'cart-items': string;
  'checkout-btn': string;
  'cont-shopping-btn': string;
  'delete-btn-container': string;
  'general-info': string;
  'image-container': string;
  'info': string;
  'item': string;
  'item-container': string;
  'items': string;
  'links': string;
  'product-info': string;
  'productid': string;
  'summary': string;
  'title': string;
  'variation': string;
}
export const cssExports: CssExports;
export default cssExports;
