// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'categories-container': string;
  'content': string;
  'image': string;
  'item': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
