// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'categorypage-container': string;
  'components': string;
  'dropdown': string;
  'selection': string;
}
export const cssExports: CssExports;
export default cssExports;
