// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contact-top-level-list': string;
  'first-top-level-list': string;
  'footer-container': string;
  'list': string;
  'list-content': string;
  'useful-links-list': string;
  'useful-links-top-level-list': string;
}
export const cssExports: CssExports;
export default cssExports;
