// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'icon': string;
  'icon-container': string;
  'image': string;
  'image-content': string;
  'popularproducts-container': string;
  'popularproducts-container-wrap': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
