// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'add-to-cart-button': string;
  'add-to-cart-disabled-button': string;
  'button': string;
  'buttons': string;
  'color-selection': string;
  'desc': string;
  'image': string;
  'image-container': string;
  'info': string;
  'input': string;
  'input-text': string;
  'like-button': string;
  'liked': string;
  'likes': string;
  'not-liked': string;
  'price': string;
  'productpage-container': string;
  'propertylist': string;
  'quantity': string;
  'selected-button': string;
  'selection-button': string;
  'selection-content': string;
  'size-selection': string;
  'size-selection-buttons': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
