// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'gotohome': string;
  'item': string;
  'order-items': string;
  'order-items-container': string;
  'profile-info': string;
  'profilepage-container': string;
}
export const cssExports: CssExports;
export default cssExports;
