// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'column': string;
  'form': string;
  'input-container': string;
  'register-container': string;
}
export const cssExports: CssExports;
export default cssExports;
