// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'cart': string;
  'cart-button': string;
  'company-logo': string;
  'image': string;
  'logo-buttons-container': string;
  'navbar': string;
  'right-side-buttons': string;
  'search-container': string;
  'search-icon': string;
  'search-input': string;
}
export const cssExports: CssExports;
export default cssExports;
