// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form': string;
  'input-text': string;
  'newsletter-container': string;
  'submit-button': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
