// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'company-logo': string;
  'content': string;
  'image': string;
  'link': string;
  'unsubnewsletter-container': string;
}
export const cssExports: CssExports;
export default cssExports;
